      SUBROUTINE AORAD
     &    (NSTEP , KLON  , NLEV   , NLEVP1,
     &     KSTART, KSTOP , CONACC , DTIME  , TWODT ,
     &     NCBASE, NTBASE, NTIMST ,
     &     NMONTH, NRADFR, LRAD   ,
     &     LSOLC , LAER  , LCFC   , LGADSRH,
C          -- PROGNOSTIC FIELDS AND TENDENCIES --
     &     TM1, QM1, TE, XM1,
C          -- PRESSURE FIELDS AND MASKS --
     &     APM1, APHM1, LOLAND, LOGLAC,
C          -- GRID COORDINATES --
     &     SINLAT, COSLAT, SINLON, COSLON,
C          -- SURFACE FIELDS AND CLOUD COVER --
     &     TSM1M, SNM1M, SRFL, ACLC,
CTS CHANGE FOR LAND-SEA-SEAICE DIFFERENTIATION
     &     TSLM1M, TSIM1M, INFRL, INFRW, INFRI,
CTS 250100
C          -- VEGETATION PARAM. AND ALBEDOS --
CTS CHANGE FOR LAND-SEA-SEAICE DIFFERENTIATION
     &     FOREST, ALB, ALBEDO,
     &     ALSOL, ALSOW, ALSOI,
CTS 250100
C          --  EMISSIVITIES ---
     &     EMTER, TRSOL, EMTEF, TRSOF,
C          -- REMAINING ELEMENTS IN *RADHEAT* --
     &     ACLCV , SRADS , SRADSU, SRAD0 ,
     &     SRAD0U, TRADS , TRADSU, TRAD0 ,
     &     SCLF0 , SCLFS , SRAF0 , SRAFS ,
     &     TCLF0 , TCLFS , TRAF0 , TRAFS ,
     &     CVDAES, CVDAEL, CVDAEU, CVDAED,
     &     OZONPL, NOZ   , PSO4ALL, PSO4NAT)
      !
      IMPLICIT NONE
      !
      !
      ! Dummy Arguments
      !
      INTEGER, INTENT(IN) :: NSTEP , KLON  , NLEV   , NLEVP1,
     &     KSTART, KSTOP , NCBASE, NTBASE, NTIMST ,
     &     NMONTH, NRADFR, NOZ
      REAL, INTENT(IN)    :: CONACC, DTIME, TWODT
C
C     DECLARATIONS
C
C          -- PROGNOSTIC FIELDS AND TENDENCIES --
      REAL, INTENT(IN) :: TM1(KLON,NLEV), TE (KLON,NLEV),
     &     QM1(KLON,NLEV), XM1(KLON,NLEV),
C           -- PRESSURE FIELDS --
     &     APM1(KLON,NLEV), APHM1(KLON,NLEVP1),
C          -- GRID COORDINATES AND SURFACE FIELDS --
     &     SINLAT(KLON), COSLAT(KLON), SINLON(KLON), COSLON(KLON)   ,
     &     TSM1M(KLON) , SNM1M(KLON) , SRFL(KLON)  , ACLC(KLON,NLEV),
CTS CHANGE FOR LAND-SEA-SEAICE DIFFERENTIATION
     &     FOREST(KLON), ALB(KLON)   , 
     &     TSLM1M(KLON), TSIM1M(KLON)
      REAL, INTENT(INOUT) :: ALBEDO(KLON), ALSOL(KLON), 
     &     ALSOW(KLON) , ALSOI(KLON) 
CTS 250100
      REAL, INTENT(INOUT) ::
C          -- EMISSIVITIES ---
     &     EMTER(KLON,NLEVP1), TRSOL(KLON,NLEVP1),
     &     EMTEF(KLON,2)     , TRSOF(KLON,2)
      REAL, INTENT(IN) ::
C          -- REMAINING ELEMENTS IN *RADHEAT* --
     &     SRADS(KLON), SRADSU(KLON), SRAD0(KLON),
     &     SRAD0U(KLON), TRADS(KLON), TRADSU(KLON), TRAD0(KLON),
     &     SCLF0(KLON) , SCLFS(KLON), SRAF0(KLON) , SRAFS(KLON),
     &     TCLF0(KLON) , TCLFS(KLON), TRAF0(KLON) , TRAFS(KLON),
     &     CVDAES(NLEVP1), CVDAEL(NLEVP1),
     &     CVDAEU(NLEVP1), CVDAED(NLEVP1),
     &     OZONPL(KLON,NOZ), PSO4ALL(KLON,NLEV),
     &     PSO4NAT(KLON,NLEV)
      REAL, INTENT(INOUT) :: ACLCV(KLON) 
C          -- LAND MASK + ICE MASK --
      LOGICAL, INTENT(IN) :: LOLAND(KLON), LOGLAC(KLON)
CTS CHANGE FOR LAND-SEA-SEAICE DIFFERENTIATION
      INTEGER, INTENT(IN) :: INFRL(KLON), INFRW(KLON), INFRI(KLON)
CTS 250100
C
      LOGICAL, INTENT(IN) :: LRAD, LSOLC, LAER, LCFC, LGADSRH
C
C*    4.1   COMPUTE RADIATION TENDENCIES.
C
      CALL PRERAD(NSTEP , DTIME , NCBASE, NTBASE,
     &            NTIMST, NMONTH, NRADFR)
C
C
      IF (NSTEP.EQ.0.OR.MOD(NSTEP+1,NRADFR).EQ.0) THEN
C
         CALL AORADINT
     &    (KLON, NLEV , NLEVP1, KSTART, KSTOP,
     &     LRAD, LSOLC, LAER  , LCFC  , LGADSRH,
C          -- PROGNOSTIC FIELDS AND TENDENCIES --
     &     TM1, XM1, QM1,
C          -- PRESSURE FIELDS AND MASKS --
     &     APM1, APHM1, LOLAND, LOGLAC,
C          -- GRID COORDINATES --
     &     SINLAT, COSLAT, SINLON, COSLON,
C          -- SURFACE FIELDS FIELDS  --
     &     TSM1M, SNM1M , ACLC  , FOREST,
CTS CHANGE FOR LAND-SEA-SEAICE DIFFERENTIATION
     &     ALB   , ALBEDO,
     &     TSLM1M, TSIM1M, INFRL, INFRW, INFRI,
     &     ALSOL , ALSOW , ALSOI ,
CTS 250100
C          -- EMISSIVITIES ---
     &     EMTER, TRSOL, EMTEF, TRSOF,
C          -- REMAINING ELEMENTS IN *RADINT* --
     &     ACLCV, CVDAES, CVDAEL, CVDAEU, CVDAED,
     &     OZONPL, NOZ, PSO4ALL, PSO4NAT)
C
      ENDIF
C
C*         4.2   ADD RADIATION TENDENCIES EVERY TIME STEP.
C
      CALL RADHEAT
     &    (KLON  , NLEV  , NLEVP1,
     &     KSTART, KSTOP , CONACC, TWODT,
     &     LRAD  ,
C          -- PROGNOSTIC FIELDS AND TENDENCIES --
     &     TM1, TE, QM1,
C          -- PRESSURE FIELDS --
     &     APM1, APHM1,
C          -- GRID COORDINATES --
     &     SINLAT, COSLAT, SINLON, COSLON,
C          -- SURFACE FIELDS  --
     &     TSM1M, SRFL, ALBEDO,
C          -- EMISSIVITIES ---
     &     EMTER, TRSOL, EMTEF, TRSOF,
C          -- REMAINING ELEMENTS IN *RADHEAT* --
     &     SRADS, SRADSU, SRAD0, SRAD0U,
     &     TRADS, TRADSU, TRAD0,
     &     SCLF0, SCLFS , SRAF0, SRAFS ,
     &     TCLF0, TCLFS , TRAF0, TRAFS)
C
      RETURN
      END SUBROUTINE AORAD
