C
      REAL ::          DLAND, DNOPRC
C
      COMMON /COMCONV/ DLAND, DNOPRC
C
C**
C**** COMCONV -   CB:WERTE FUER ZDLAND UND ZDNOPRC IN CEASC
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**
C**   DLAND   :   MINIMALE DICKE DER WOLKE UEBER LAND, DAMIT ES
C**               AUS IHR REGNEN KANN  [DM] !!
C**   DEFAULT :   FUER EUROPA=7.5E3 (ORIGINAL ECHAM4=1.5E4)
C**   DNOPRC  :   MINIMALE DICKE DER WOLKE UEBER WASSER, DAMIT ES
C**               AUS IHR REGNEN KANN  [DM] !!
C**   DEFAULT :   FUER EUROPA=7.5E3 (ORIGINAL ECHAM4=1.5E4)
C**
C**   VERFASSER:   R.PODZUN
