C
      LOGICAL ::          LMOMON, LDIA
C
      INTEGER ::          KFL800, KFL400
C
      COMMON  / COMDIA /  LMOMON, LDIA, KFL800, KFL400
C**
C**** COMDIA   -   CB:STEUERPARAMETER DER MODELL-DIAGNOSE
C**
C**   LMOMON   :   WENN .TRUE. MODELLMONATE (30 TAGE) SONST KALENDERMONATE
C**
C**   LDIA     :   WENN .TRUE. AUSGABE VON TITELBLATT, NAMELIST-VARIABLEN
C**                SOWIE FLAECHENMITTELWERTEN JEDEN ZEITSCHRITT IM OUTPUT
C**
C**   KFL800   :   K-INDEX DER EM-HAUPTFLAECHE, DEREN DRUCK ETWA 800 HPA
C**                BETRAEGT
C**   KFL400   :   K-INDEX DER EM-HAUPTFLAECHE, DEREN DRUCK ETWA 400 HPA
C**                BETRAEGT
C**
C**   VERFASSER:   D.MAJEWSKI
