C
      LOGICAL             LHYDRO,LZDIFFT,LZDIFFQD

      COMMON  / COMHYD /  LHYDRO,LZDIFFT,LZDIFFQD
C**** COMHYD   -   CB:STEUERPARAMETER FUER HYDROSTATISCHE BERECHNUNG
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**   LHYDRO   :   TRUE  NICHTHYDROSTATISCHE BERECHNUNG
C**                FALSE HYDROSTATISCHE BERECHNUNG
C**   LZDIFFT  :   TRUE  TEMPERATUR WIRD AUF P-FLAECHEN DIFFUNDIERT
C**                FALSE TEMPERATUR WIRD AUF SIGMA-FLAECHEN DIFFUNDIERT
C**   LZDIFFQD :   TRUE  FEUCHTE WIRD AUF P-FLAECHEN DIFFUNDIERT
C**                FALSE FEUCHTE WIRD AUF SIGMA-FLAECHEN DIFFUNDIERT
C**
C**   VERFASSER:   H.GOETTEL
