C
C@(#) BIBLIOTHEK EM: EUROPA-MODELL / DEUTSCHLAND-MODELL
C@(#) MODUL COMNMI.H, V2.12 VOM 4/27/94, EXTRAHIERT AM 4/28/94
C
C
      LOGICAL ::          LANMI, LDNMI
C
      INTEGER ::          NVM , NITNMI
C
      REAL    ::          DTNMI     
C
      COMMON  / COMNMI /  LANMI, LDNMI, NVM , NITNMI, DTNMI
C**** COMNMI   -   CB:STEUERPARAMETER DER INITIALISIERUNG
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**   LANMI    :   TRUE:  ADIABATISCHE NORMAL MODE INITIALIS. (--)
C**                FALSE: OHNE NMI
C**   LDNMI    :   TRUE:  DIABATISCHE NORMAL MODE INITIALIS.  (--)
C**                FALSE: OHNE DIABATISCHE NMI
C**   NVM      :   ANZAHL DER VERTIKALEN MODES BEI DER NMI    (--)
C**   NITNMI   :   ANZAHL DER ITERATIONEN BEI DER NMI         (--)
C**   DTNMI    :   ZEITSCHRITT BEI NMI                        (S)
C**
C**   VERFASSER:   D.MAJEWSKI
