C
      LOGICAL   ::        LPHY, LAKKU
C
      COMMON  / COMPHY /  LPHY, LAKKU
C
C**** COMPHY   -   CB:STEUERPARAMETER DER DIABATISCHEN PROGNOSE
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**   LPHY     :   TRUE:  PROGNOSE MIT VOLLER PHYSIK          (--)
C**                FALSE: ADIABATISCHE PROGNOSE (MIT H-DIFF.)
C**   LAKKU    :   TRUE:  PROGNOSE MIT  SUMMIERTEM NIEDERSCHL.(--)
C**                FALSE: PROGNOSE OHNE SUMMIERTEM NIEDERSCHL.
C**
C**   VERFASSER:   D.MAJEWSKI/R. PODZUN
