C
C     COMMON-BLOCK CORG2 NUR ZUSAMMEN MIT COMMON-BLOCK CORG VERWENDEN
C
      CHARACTER YDVARND(NZMXVD)*8, YTVARND(NZMXVT)*8
      CHARACTER YMVARND(NZMXVM)*8, YNVARND(NZMXVN)*8
C
      COMMON / CORG2 / YDVARND, YTVARND, YMVARND, YNVARND
C
C     VERFASSER: R. PODZUN
C
