C
      INTEGER, PARAMETER :: 
     &            NZMXVA=178, NZMXVR=40 , NZMXVD=77, NZMXVN=140,
     &            NZMXVT=157, NZMXVF=178, NZMXVB= 3, NZMXVM=140

      CHARACTER         YADEN          * 3, YADCAT  *56, YADNAM *18,
     &                  YAVARN(NZMXVA) * 8,
     &                  YRDEN          * 3, YRDCAT  *56, YRDNAM *18,
     &                  YRVARN(NZMXVR) * 8,
     &                  YEDEN          * 3, YEDCAT  *56,
     &                  YDDEN          * 3, YDDCAT  *56, YDDNAM *18,
     &                  YDVARN(NZMXVD) * 8,
     &                  YFDEN          * 3, YFDCAT  *56, YFDNAM *18,
     &                  YFVARN(NZMXVF) * 8,
     &                  YTDEN          * 3, YTDCAT  *56, YTDNAM *18,
     &                  YTVARN(NZMXVT) * 8,
     &                  YSDNAM         *14, YMDCAT  *56, YMDNAM *14,
     &                                      YNDCAT  *56,
     &                  YMVARN(NZMXVM) * 8, YEDNAM(NZMXVM) *24,
     &                  YNVARN(NZMXVN) * 8, YNDNAM(NZMXVN) *24,
     &                  YBDCAT         *64, YBDNAM(NZMXVB) *64,
     &                  YGDCAT         *64, YGDNAM  *64,
     &                  YHDCAT         *64, YHDNAM  *64,
     &                  YO3DCAT        *64, YO3DNAM *64,
     &                  YSADCAT        *64, YSADNAM *64,
     &                  YSNDCAT        *64, YSNDNAM *64

      CHARACTER          YADAT*10, YAKDAT1*10, YAKDAT2*21,
     &                   YUSERA*3, YUSERE*3  , YANDAT*10

      COMMON  / CORG  /  YADEN  , YADCAT , YADNAM , YAVARN ,
     &                   YRDEN  , YRDCAT , YRDNAM , YRVARN ,
     &                   YEDEN  , YEDCAT , YEDNAM ,
     &                   YDDEN  , YDDCAT , YDDNAM , YDVARN ,
     &                   YFDEN  , YFDCAT , YFDNAM , YFVARN ,
     &                   YTDEN  , YTDCAT , YTDNAM , YTVARN ,
     &                   YSDNAM , YMDCAT , YMDNAM , YMVARN ,
     &                            YNDCAT , YNDNAM , YNVARN ,
     &                   YADAT  , YAKDAT1, YAKDAT2, YANDAT ,
     &                   YUSERA , YUSERE , YBDCAT , YBDNAM ,
     &                   YGDCAT , YGDNAM , YO3DCAT, YO3DNAM,
     &                   YSADCAT, YSADNAM, YSNDCAT, YSNDNAM,
     &                   YHDCAT , YHDNAM

C**** CORG     -   CB:CHARACTER-GROESSEN FUER DIE DATEIENVERWALTUNG
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**   YADEN    :   EXPERIMENTNAME DER ANFANGSDATEN
C**   YADCAT   :   CATALOG-NAME DER ANFANGSDATEN
C**   YADNAM   :   NAME DER DATEI MIT DEN ANFANGSDATEN
C**   YAVARN   :   NAMEN DER FELDER, DIE IN A-DATEI STEHEN MUESSEN
C**   NZMXVA   :   DIMENSIONIERUNG VON YAVARN; AKTUELLE ANZAHL VON
C**                VARIABLENNAMEN STEHT IN CB 'ORG' IN NZVA
C**
C**   FUER DIE RAND-('R'), ERGEBNIS-('E'), DM-AUSSCHNITT-('D') ,
C**   TRAJEKTORIEN- ('T'), UND DIE FORTSETZUNGSDATEN ('F') SIND DIE
C**   GROESSEN EBENSO DEFINIERT.
C**
C**   YMDNAM   :   NAME DER DATEI MIT DEN MONATSMITTELWERTEN
C**   YSDNAM   :   NAME DER DATEI MIT DEN STANDARDABWEICHUNGEN
C**   YMDCAT   :   CATALOG-NAME DER MONATSMITTELWERTE UND STDABW.
C**   YMVARN   :   NAMEN DER FELDER, DIE IN M-DATEI STEHEN MUESSEN
C**
C**   YNDNAM   :   NAME DER DATEI(EN) MIT DEN TAGESMITTELWERTEN
C**   YNDCAT   :   CATALOG-NAME DER TAGESMITTELWERTDATEI(EN)
C**   YNVARN   :   NAMEN DER FELDER, DIE IN TAGESMITTELDATEI(EN)
C**                STEHEN MUESSEN
C**
C**   YBDCAT   :   CATALOG-NAME DER BODENDATEN
C**   YBDNAM   :   NAMEN DER DATEIEN MIT DEN BODENDATEN
C**   YGDCAT   :   CATALOG-NAME DER ZEITL. VARIABLEN GREENHOUSE GASE
C**   YGDNAM   :   NAMEN DER DATEIEN MIT DEN ZEITL. VARIABLEN
C**                GREENHOUSE GASEN
C**   YO3DCAT  :   CATALOG-NAME DER ZEITL. VARAIABLEN OZON FELDER
C**   YO3DNAM  :   NAMEN DER DATEIEN MIT DEN ZEITL. VARAIABLEN
C**                OZON FELDERN
C**   YSADCAT  :   CATALOG-NAME DER ZEITL. VARAIABLEN AEROSOL FELDER
C**                (SO4ALL)
C**   YSADNAM  :   NAMEN DER DATEIEN MIT DEN ZEITL. VARAIABLEN
C**                AEROSOL FELDERN (ALL)
C**   YSNDCAT  :   CATALOG-NAME DER ZEITL. VARAIABLEN AEROSOL FELDER
C**                (SO4NAT)
C**   YSNDNAM  :   NAMEN DER DATEIEN MIT DEN ZEITL. VARAIABLEN
C**                AEROSOL FELDERN (NAT)
C**   YHDCAT   :   CATALOG-NAME DES RESTARTFILES FUER DIE MITTELBILDUNG
C**   YHDNAM   :   NAMEN DES RESTARTFILES FUER DIE MITTELBILDUNG
C**
C**   YADAT    :   ANFANGSDATUM DES MODELL-LAUFES
C**                YYYYMMDDHH (JAHR, MONAT, TAG, STUNDE)
C**   YAKDAT1  :   AKTUELLES DATUM (=YADAT+NZT/DT) IN DER FORM YYYYMMDDHH
C**   YAKDAT2  :   AKTUELLES DATUM (=YADAT+NZT/DT) IN DER FORM:
C**                WD DD.MM.YY  HH UTC   MIT WD:WOCHENTAG
C**   YANDAT   :   ANFANGSDATUM DES AKTUELLEN MODELLJOBS
C**                YYYYMMDDHH (JAHR, MONAT, TAG, STUNDE)
C**   YUSERA   :   REMO-USER-NUMMER DER INPUT-DATEIEN
C**   YUSERE   :   REMO-USER-NUMMER DER OUTPUT-DATEIEN
C**                REMO-USER-NUMMERN WERDEN DURCH: R. PODZUN,
C**                M&D, MPIFM VERGEBEN
C**
C**   VERFASSER:   R. PODZUN/ D. MAJEWSKI
