C
C     SUBROUTINE DATEINDBL
C
C**** DATEIN   -   UP:LESEN EINES FELDES
C**   AUFRUF   :   CALL DATEINDBL(NUDAT, UFELD, IEJE, ZAK, ZBK, KEMAX, ISTAT)
C**   ENTRIES  :   KEINE
C**   ZWECK    :   LESEN EINES FELDES
C**   VERSIONS-
C**   DATUM    :   20.01.99
C**
C**   EXTERNALS:   KEINE
C**
C**   EINGABE-
C**   PARAMETER:   NUDAT: LOGISCHE EINHEIT (UNIT-NUMBER) DER DATEI, VON
C**                       DER GELESEN WERDEN SOLL
C**                UFELD: ARRAY FUER EIN FELD
C**                IEJE : DIMENSIONIERUNG VON UFELD IM RUFENDEN
C**                       PROGRAMM
C**   AUSGABE-
C**   PARAMETER:   UFELD: ARRAY FUER EIN FELD
C**                ISTAT: STATUSPARAMETER; FEHLERFREI FUER ISTAT=0,
C**                       FUER ISTAT=1 AM ENDE DER DATEI ANGELANGT.
C**   COMMON-
C**   BLOECKE  :   GRIB
C**
C**   METHODE  :   -
C**
C**   FEHLERBE-
C**   HANDLUNG :   KEINE
C**   VERFASSER:   R.PODZUN
C
      SUBROUTINE DATEINDBL(NUDAT, UFELD, IEJE, ZAK, ZBK, KEMAX, ISTAT)
C
      IMPLICIT NONE
C
      INCLUDE "grib.h"
C
C     Dummy Arguments
C
      INTEGER, INTENT(IN)     :: NUDAT, IEJE, KEMAX
      REAL,    INTENT(INOUT)  :: UFELD(IEJE), ZAK(KEMAX), ZBK(KEMAX)
      INTEGER, INTENT(OUT)    :: ISTAT
C
C     Local Variables
C
      REAL    :: REF
      INTEGER :: I,J,IER
C
C     FELD EINLESEN
C
      READ(NUDAT,END=999,ERR=998,IOSTAT=IER) IPDB,(IGDB(I),I=1,18),REF,
     &               (IGDB(J),J=20,22),ZAK,ZBK
      READ(NUDAT) UFELD
C
C 
      ISTAT=0
      RETURN
C
 998  CONTINUE
      PRINT *,'FEHLER IN DATEIN, IOSTAT= ',IER
      STOP 'ERROR'
C
 999  CONTINUE
      ISTAT=1
C
      RETURN
      END
