      SUBROUTINE DATEIN(NUDAT, UFELD, IEJE, ZAK, ZBK, KEMAX, ISTAT)
C
      IMPLICIT NONE
C
C**** DATEIN   -   UP:LESEN EINES FELDES
C**   AUFRUF   :   CALL DATEIN(NUDAT, UFELD, IEJE, ZAK, ZBK, KEMAX, ISTAT)
C**   ENTRIES  :   KEINE
C**   ZWECK    :   LESEN EINES FELDES
C**   VERSIONS-
C**   DATUM    :   20.01.99
C**
C**   EXTERNALS:   KEINE
C**
C**   EINGABE-
C**   PARAMETER:   NUDAT: LOGISCHE EINHEIT (UNIT-NUMBER) DER DATEI, VON
C**                       DER GELESEN WERDEN SOLL
C**                UFELD: ARRAY FUER EIN FELD
C**                IEJE : DIMENSIONIERUNG VON UFELD IM RUFENDEN
C**                       PROGRAMM
C**   AUSGABE-
C**   PARAMETER:   UFELD: ARRAY FUER EIN FELD
C**                ISTAT: STATUSPARAMETER; FEHLERFREI FUER ISTAT=0,
C**                       FUER ISTAT=1 AM ENDE DER DATEI ANGELANGT.
C**   COMMON-
C**   BLOECKE  :   GRIB
C**
C**   METHODE  :   -
C**
C**   FEHLERBE-
C**   HANDLUNG :   KEINE
C**   VERFASSER:   R.PODZUN
C
      INCLUDE "grib.h"
C
      INTEGER, INTENT(IN) :: NUDAT, KEMAX, IEJE
      INTEGER, INTENT(OUT) :: ISTAT
      DOUBLE PRECISION, INTENT(INOUT) :: UFELD(IEJE), ZAK(KEMAX), 
     &                                   ZBK(KEMAX)    
C
C     Local Variables
C
      INTEGER :: I, J, IJ, IER
      REAL    :: RREF
      REAL    :: RUFELD(IEJE), RZAK(KEMAX), RZBK(KEMAX)
C
C     FELD EINLESEN
C
      READ(NUDAT,END=999,ERR=998,IOSTAT=IER) IPDB,(IGDB(I),I=1,18),RREF,
     &               (IGDB(J),J=20,22),RZAK,RZBK
      READ(NUDAT) RUFELD
C
      DO IJ=1,KEMAX
         ZAK(IJ)=RZAK(IJ)
         ZBK(IJ)=RZBK(IJ)
      ENDDO
      DO IJ=1,IEJE
         UFELD(IJ)=RUFELD(IJ)
      ENDDO
C
      ISTAT=0
      RETURN
C
 998  CONTINUE
      PRINT *,'FEHLER IN DATEIN, IOSTAT= ',IER
      STOP 'ERROR'
C
 999  CONTINUE
      ISTAT=1
C
      RETURN
      END SUBROUTINE DATEIN
