C
      INTEGER      NEMGBNR(NFLDEM), NEMGBLT(NFLDEM), KAKE(NFLDEM,2),
     &             NZEMTLV(NFLDEM), NGBTRI (NFLDEM)
      REAL         EMGBFK (NFLDEM), EMGBBS (NFLDEM)
C
      COMMON / EMGBRI / NEMGBNR, NEMGBLT, EMGBFK, EMGBBS, KAKE, NZEMTLV,
     &                  NGBTRI
C
C**** EMGBRI   -   CB:TABELLEN MIT DER GRIB-CODE-NUMMER, FAKTOR, BIAS
C****                 UND UNTER- UND OBERGRENZE DER FELDER DES EM, DIE
C****                 AUSGEGEBEN WERDEN KOENNEN
C****                 *EMGBCH* UND *EMGBRI* GEHOEREN ZUSAMMEN.
C**   NFLDEM   :   ANZAHL DER NAMEN IN DER TABELLE YEMNAME
C**
C**   NEMGBNR  :   GRIB-NUMMER DES EM-FELDES
C**   NEMGBLT  :   FLAECHENTYP DES EM-FELDES
C**   NZEMTLV  :   ANZAHL DER ZEITEBENEN IM EM (1, 2 ODER 3)
C**   EMGBFK   :   GRIB-FAKTOR DES EM-FELDES
C**   EMGBBS   :   GRIB-BIAS   DES EM-FELDES
C**                FAKTOR UND BIAS WERDEN BENOETIGT, UM VON EM-EINHEITEN
C**                AUF GRIB-EINHEITEN UMZURECHNEN.
C**                FELD(GRIB) = (FELD(EM  ) + BIAS ) * FAKTOR
C**                FELD(EM  ) =  FELD(GRIB) / FAKTOR - BIAS
C**   NGBTRI   :   TIME RANGE INDICATOR IM GRIB-CODE
C**
C**   KAKE     :   OBER- UND UNTERGRENZE DES FELDES
C**                BEI FELDERN, VON DENEN NUR EIN NIVEAU VORLIEGT, IST
C**                OBERGRENZE = UNTERGRENZE.
C**
C**   VERFASSER:   D.MAJEWSKI
