C
      INTEGER, PARAMETER  :: NFLDEM = 182
      CHARACTER           :: YEMNAME(NFLDEM)*8
C
      COMMON / EMGBCH / YEMNAME
C
C**** EMGBCH   -   CB:TABELLE MIT DEN NAMEN DER IM EM DEFINIERTEN
C****                 FELDER, DIE AUSGEGEBEN WERDEN KOENNEN.
C****                 *EMGBCH* UND *EMGBRI* GEHOEREN ZUSAMMEN.
C**   BESCHREIBUNG DER VARIABLEN:
C**
C**   YEMNAME  :   TABELLE MIT DEN NAMEN DER EM-FELDER
C**
C**   VERFASSER:   D.MAJEWSKI
