C
      REAL    ::         FAKINF, EDFAKINF
C
      COMMON / FAKTINF / FAKINF, EDFAKINF
C
C**   BESCHREIBUNG DER VARIABLEN:
C**
C**   FAKINF   : GENAUIGKEIT DES FRAKTIONELLEN ANTEILS VON
C**              LAND/WASSER/SEE-EIS (100. = PROZENT)
C**   EDFAKINF : 1./FAKINF
