      SUBROUTINE FILTER(F, FILT)
C**** FILTER   -   FILTERN EINES FELDES MIT DIGITALEN iFILTERN DER LAENGE
C****              4 ODER 8
C**   AUFRUF   :   CALL FILTER ( F, IE, JE, FILT, NE, ME )
C**   ZWECK    :   AUFRUF EINES GEWUENSCHTEN FILTERS ZUR GLAETTUNG EINES
C**                BELIEBIGEN ZWEIDIMENSIONALEN FELDES
C**   VERSIONS-
C**   DATUM    :   03.MAI 1989
C**   EXTERNALS:   FILTER4, FILTER8
C**   EINGABE-
C**   PARAMETER:   F        -   ZWEIDIMENSIONALES FELD
C**                IE       -   1.DIMENSION DES FELDES
C**                JE       -   2.DIMENSION DES FELDES
C**                NE       -   GEWUENSCHTE FILTERLAENGE (4 ODER 8)
C**   AUSGABE-
C**   PARAMETER:   FILT -  GEFILTERTES FELD
C**   METHODE  :   AUFRUF VON FILTER4 ODER FILTER8
C**   FEHLERBE-
C**   HANDLUNG :   ................
C**   VERFASSER:   V.WOHLGEMUTH/D.MAJEWSKI
C     SP1(IE),SP2(IE),SP3(IE) HILFSSPEICHER
C
      IMPLICIT NONE
C
      INCLUDE "parorg.h"
C
      REAL, INTENT(IN)    :: F(MOIE,MOJE)
      REAL, INTENT(INOUT) :: FILT(MOIE,MOJE)
C
      REAL :: SP1(MOIE), SP2(MOJE), SP3(MOJE), SP4(MOJE)
C
      INTEGER :: I,J
C
      DO J = 1,MOJE
         CALL FILTER4(F(1:MOIE,J), SP1, FILT(1:MOIE,J), MOIE)
      ENDDO
C
      DO I = 1,MOIE
C

         DO J = 1,MOJE
            SP4(J)  = FILT(I,J)
         ENDDO
C
         CALL FILTER4(SP4, SP2, SP3, MOJE)
C
         DO J = 1,MOJE
            FILT(I,J) = SP3(J)
         ENDDO
C
      ENDDO
C
      RETURN
      END SUBROUTINE FILTER
