      SUBROUTINE GETD(NUDAT, YDNAM, YDCAT)
C
C**** GETD     -   UP:OEFFNEN VON EM-DATTEIEN
C**   AUFRUF   :   SUBROUTINE GETD(NUDAT, YDNAM, YDCAT)
C**
C**   ENTRIES  :   KEINE
C**   ZWECK    :   OEFFNEN DER EM- ANFANGS- UND RANDDATEIEN
C**
C**   VERSIONS-
C**   DATUM    :   20.01.99
C**
C**   EXTERNALS:   LENCH, PRTLOG
C**
C**   EINGABE-
C**   PARAMETER:   NUDAT:   LOGISCHE EINHEIT (UNIT-NUMBER) MIT DER DIE
C**                         ZU HOLENDE DATEI VERKNUEPFT WERDEN SOLL
C**                YDNAM:   PERMANENTER/LOKALER DATEI-NAME
C**                YDCAT:   CATALOG, IN DEM DIE GRIB-CODE-DATEI LIEGT
C**   AUSGABE-
C**   PARAMETER:   ISTAT:   STATUS-PARAMETER; ISTAT=0: DATEN SIND GEHOLT
C**
C**   COMMON-
C**   BLOECKE  :   KEINE
C**
C**   METHODE  :   AUFRUF VON OPEN
C**
C**   FEHLERBE-
C**   HANDLUNG :   FEHLERSCHLUESSEL SETZEN
C**   VERFASSER:   R.PODZUN
C
      IMPLICIT NONE
C
C     Dummy Arguments
C
      INTEGER,       INTENT(IN) :: NUDAT
      CHARACTER*(*), INTENT(IN) :: YDNAM, YDCAT
      CHARACTER                 :: YPFAD*128, YBTEXT*136
C
C     Local Variables
C
      INTEGER :: ILYBTEX,ILYPFAD,ILYDNAM,ILYDCAT,ISTAT
      INTEGER, EXTERNAL :: LENCH
C
      YBTEXT  = ' '
C
C     LAENGE DES CATALOG-NAMENS FESTSTELLEN
      ILYDCAT = LENCH(YDCAT)
C
C     PFADNAME DER DATEI ERSTELLEN
      ILYDNAM = LENCH(YDNAM)
      YPFAD   = YDCAT(1:ILYDCAT)//YDNAM(1:ILYDNAM)
      ILYPFAD = LENCH(YPFAD)
      YBTEXT = 'OPEN:   '//YPFAD
      ILYBTEX = LENCH(YBTEXT)
      CALL PRTLOG(YBTEXT(1:ILYBTEX))
      OPEN(NUDAT,FORM='UNFORMATTED',FILE=YPFAD(1:ILYPFAD),IOSTAT=ISTAT)
      IF (ISTAT.NE.0) THEN
         PRINT *,'GETD: FEHLER IN OPEN',YPFAD(1:ILYPFAD)
         STOP
      ENDIF
C
      RETURN
      END
