      SUBROUTINE GETLOC (IVLOC)
C
C**** GETLOC   -   UP:PLATZ DES FELDNAMENS IN DER TABELLE DER EM-VARIAB-
C****                 LEN-NAMEN FINDEN
C**   AUFRUF   :   CALL GETLOC(IVLOC)
C**   ENTRIES  :   KEINE
C**   ZWECK    :   PLATZ DES FELDNAMENS IN DER TABELLE DER EM-VARIABLEN-
C**                NAMEN FINDEN, DER ZU DEM FELD GEHOERT, DESSEN
C**                GRIB-CODE-NUMMER IM IPDB(7) STEHT.
C**   VERSIONS-
C**   DATUM    :   08.02.89
C**
C**   EXTERNALS:   KEINE
C**
C**   EINGABE-
C**   PARAMETER:   KEINE
C**   AUSGABE-
C**   PARAMETER:   IVLOC: PLATZNUMMER IN DER TABELLE YEMNAME
C**                       WENN IVLOC=-1, FELD NICHT IN TABELLE
C**
C**   COMMON-
C**   BLOECKE  :   GRIB, EMGBCH, EMGBRI, EMGBDT
C**
C**   METHODE  :   SEQUENTIELLES DURCHSUCHEN DER TABELLE MIT DEN GRIB-
C**                CODE-NUMMERN (NEMGBNR), BIS IPDB(7) = NEMGBNR(NTAB).
C**   FEHLERBE-
C**   HANDLUNG :   IVLOC=-1, WENN FELD NICHT IN TABELLE
C**   VERFASSER:   D.MAJEWSKI
C
      IMPLICIT NONE
C
      INCLUDE "grib.h"
      INCLUDE "emgbch.h"
      INCLUDE "emgbri.h"
C
C     Dummy Arguments
C
      INTEGER, INTENT(OUT) :: IVLOC
C
C     Local Variable
C
      INTEGER              :: NTAB
C
      IVLOC = -1
      DO NTAB = 1, NFLDEM
         IF(IPDB(7).EQ.NEMGBNR(NTAB).AND.IPDB(8).EQ.NEMGBLT(NTAB)) THEN
            IVLOC = NTAB
            EXIT
         ENDIF
      ENDDO
C
      RETURN
      END SUBROUTINE GETLOC
