C
      INTEGER     ::     IPDB(37), IGDB(22)
C
      COMMON  / GRIB  /  IPDB,     IGDB
C
C**** GRIB     -   CB:FELDER FUER GRIB-CODE
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**   IPDB     :   PRODUCT DEFINITION  BLOCK
C**   IGDB     :   GRID    DESCRIPTION BLOCK
C**
C**   VERFASSER:   R.PODZUN
