C
C@(#) BIBLIOTHEK EM: EUROPA-MODELL / DEUTSCHLAND-MODELL
C@(#) MODUL GRID.H, V2.12 VOM 4/27/94, EXTRAHIERT AM 4/28/94
C
      REAL    ::         POLLAM, POLPHI, DLAM, DPHI, RLALU, PHILU
      INTEGER ::         IRESFAC
C
      COMMON  / GRID  /  POLLAM, POLPHI, DLAM, DPHI, RLALU, PHILU,
     &                   IRESFAC
C
C**** GRID     -   CB:GITTERKONSTANTEN DES EM
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**   POLLAM   :   GEOGR.LAENGE DES GEDREHTEN NORDPOLS (IN GRAD, E>0)
C**   POLPHI   :   GEOGR.BREITE DES GEDREHTEN NORDPOLS (IN GRAD, N>0)
C**   DLAM     :   MASCHENWEITE IN ZONALER      RICHTUNG (IN GRAD)
C**   DPHI     :   MASCHENWEITE IN MERIDIONALER RICHTUNG (IN GRAD)
C**   RLALU    :   TRANS.LAENGE DES LINKEN UNT. ECKPUNKTES (IN GRAD,E>0)
C**   PHILU    :   TRANS.BREITE DES LINKEN UNT. ECKPUNKTES (IN GRAD,N>0)
C**
C**   VERFASSER:   D.MAJEWSKI
