      INTEGER FUNCTION KYMD2C(KYMD)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: KYMD
      INTEGER, EXTERNAL   :: KDAT2C 
C          THIS FUNCTION RETURNS THE CENTURY DAY GIVEN AN INTEGER YYMMDD
C          WHERE YY IS THE YEAR
C                MM IS THE MONTH
C                DD IS THE DAY
      KYMD2C=KDAT2C(MOD(KYMD,100),MOD(KYMD/100,100),KYMD/10000)
      RETURN
      END FUNCTION KYMD2C
