      INTEGER FUNCTION MYMD2C(KYMD)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: KYMD
      INTEGER, EXTERNAL   :: MDAT2C
C          THIS FUNCTION RETURNS THE CENTURY DAY GIVEN AN INTEGER YYMMDD
C          WHERE YY IS THE YEAR
C                MM IS THE MONTH
C                DD IS THE DAY
      MYMD2C=MDAT2C(MOD(KYMD,100),MOD(KYMD/100,100),KYMD/10000)
      RETURN
      END FUNCTION MYMD2C
