      SUBROUTINE PALLREDUCER(BUF,OP)
      IMPLICIT NONE
      INCLUDE "parorg.h"
C
      INTEGER, INTENT(IN)    :: OP
      REAL,    INTENT(INOUT) :: BUF
C
      REAL :: BUF2
C
      CALL MPI_ALLREDUCE(BUF,BUF2,COUNT,P_REAL,
     &     OP,MPI_COMM_WORLD,IERROR)
C
      BUF=BUF2
      RETURN
      END SUBROUTINE PALLREDUCER
