C
      INTEGER, PARAMETER  ::  IDIMSUM=129*121, NHORPHD=32, NOZ=19
C
C**** PARAM    -  CB:DIMENSIONEN DES REMO_MPI
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**
C**   IDIMSUM  :   DIMENSION DER FELDER IN SUMFEL.H FUER DIE MONATS-
C**            :   MITTELBILDUNG. IMMER DIE ANZAHL DER HORIZONTALEN
C**            :   GITTERPUNKTE DES GESAMTEN MODELLGEBIETES (MOIEJE)
C**
C**   NHORPH   :   LAENGE DER VEKTOREN MIT DENEN DIE ECHAM4-PHYSIK
C**            :   GERECHNET WIRD
C**            :   FUER MPI-VERSION AUF 0 GESETZT (S. PHYEC.F)
C**
C**   NOZ      :   ANZAHL DER OZON-LEVEL (FUER LAEROZ=.TRUE.)
C**
C****          :   ALLGEMEINE HINWEISE:
C****
C**   MOIE     :   ANZAHL DER GITTERPUNKTE IN ZONALER      RICHTUNG
C**   MOJE     :   ANZAHL DER GITTERPUNKTE IN MERIDIONALER RICHTUNG
C**   MOKE     :   ANZAHL DER GITTERPUNKTE IN VERTIKALER   RICHTUNG
C**            :   WERDEN UEBER DIE NAMELIST EINGELESEN !
C**
C**   MAXPROC  :   ANZAHL DER MAXIMAL VERWENDBAREN PROZESSOREN
C**            :   WIRD IN PARORG.H GESETZT (Z.ZT.=4096)
C****
C**
C**   VERFASSER:   R.PODZUN
