      SUBROUTINE PRCV ( YUP, YVAR, YWERT )
C
      IMPLICIT NONE
C
C@(#) BIBLIOTHEK EM: EUROPA-MODELL / DEUTSCHLAND-MODELL
C@(#) MODUL PRCV.F, V2.12 VOM 4/27/94, EXTRAHIERT AM 4/28/94
C
C**** PRCV     -   UP:DRUCKEN VON NAMEN UND INHALT EINER CHAR-VARIABLEN
C****                 (DEBUG)
C**
C**   AUFRUF   :   CALL PRCV ( YUP, YVAR, YWERT )
C**   ZWECK    :   AUSGABE DES NAMENS UND WERTES EINER CHAR-VARIABLEN
C**                SOWOHL IN DEN DAY-FILE,ALS AUCH AUF FILE OUTPUT
C**   EXTERNALS:   REMARK
C**   EINGABE-
C**   PARAMETER:   YUP  -  NAME   DES RUFENDEN UNTERPROGRAMMES
C**                YVAR -  NAME   DER CHARACTER-VARIABLEN
C**                YWERT-  INHALT DER CHARACTER-VARIABLEN
C**   VERFASSER:   VOLKER WOHLGEMUTH,F3


      CHARACTER*(*), INTENT(IN) :: YUP, YVAR, YWERT
      CHARACTER*80  :: YMSG(3)
      INTEGER       :: I

C     YMSG VORBESETZEN UND AUSDRUCKEN
      YMSG(1) = '***** MESSAGE FROM USER-SUPPORT *****'
      YMSG(2) = '***** SUBROUTINE: '//YUP
      YMSG(3) = '***** VARIABLE: '//YVAR//' ENTHAELT: '

      DO I = 1,3
         CALL REMARK(YMSG(I))
      ENDDO

      CALL REMARK(YWERT)

      RETURN
      END SUBROUTINE PRCV
