      SUBROUTINE PRECVL(BUF)
      IMPLICIT NONE
      INCLUDE "parorg.h"
      LOGICAL, INTENT(IN) :: BUF
C
      CALL MPI_RECV(BUF,COUNT,MPI_LOGICAL,SOURCE,TYPE,
     &      MPI_COMM_WORLD,STATUS,IERROR)
C
      RETURN
      END SUBROUTINE PRECVL
