      SUBROUTINE PRECVR(BUF)
      IMPLICIT NONE
      INCLUDE "parorg.h"
      REAL, INTENT(IN) :: BUF
C
      CALL MPI_RECV(BUF,COUNT,P_REAL,SOURCE,TYPE,
     &     MPI_COMM_WORLD,STATUS,IERROR)
C
      RETURN
      END SUBROUTINE PRECVR
