      SUBROUTINE PRECVI(BUF)
      IMPLICIT NONE
      INCLUDE "parorg.h"
      INTEGER, INTENT(IN) :: BUF
C
      CALL MPI_RECV(BUF,COUNT,MPI_INTEGER,SOURCE,TYPE,
     &     MPI_COMM_WORLD,STATUS,IERROR)
C
      RETURN
      END SUBROUTINE PRECVI
