      SUBROUTINE PREDUCERR(BUF,OP)
      INCLUDE "parorg.h"
      INTEGER ROOT,OP
      REAL BUF, BUF2
C
      ROOT=0
      CALL MPI_REDUCE(BUF,BUF2,COUNT,P_REAL,
     &     OP,ROOT,MPI_COMM_WORLD,IERROR)
C
      IF (MYID .EQ. 0) THEN
         BUF=BUF2
      ENDIF

      RETURN
      END SUBROUTINE PREDUCERR
