C
C
C@(#) BIBLIOTHEK EM: EUROPA-MODELL / DEUTSCHLAND-MODELL
C@(#) MODUL PRIV.F, V2.12 VOM 4/27/94, EXTRAHIERT AM 4/28/94
C
C**** PRIV     -   UP:DRUCKEN VON NAMEN UND WERT EINER INT-VARIABLEN
C****                 (DEBUG)
C**
C**   AUFRUF   :   CALL PRIV ( YUP, YVAR, IWERT )
C**   ZWECK    :   AUSGABE DES NAMENS UND WERTES EINER INT-VARIABLEN
C**                SOWOHL IN DEN DAY-FILE,ALS AUCH AUF FILE OUTPUT
C**   EXTERNALS:   REMARK
C**   EINGABE-
C**   PARAMETER:   YUP  -  NAME DES RUFENDEN UNTERPROGRAMMES
C**                YVAR -  NAME DER INTEGER-VARIBLEN
C**                IWERT-  WERT DER INTEGER-VARIABLEN
C**   VERFASSER:   VOLKER WOHLGEMUTH,F3
C
      SUBROUTINE PRIV ( YUP, YVAR, IWERT )
C
      IMPLICIT NONE
C
      INTEGER,       INTENT(IN) :: IWERT
      CHARACTER*(*), INTENT(IN) :: YUP, YVAR
C
      CHARACTER*80  :: YMSG(2)
      INTEGER       :: I

C     YMSG  VORBESETZEN
      YMSG(1) = '***** MESSAGE FROM USER-SUPPORT *****'
      DO I = 1,80
         YMSG(2)( I: I) = ' '
      ENDDO

C     YUP, YVAR , IWERT IN DEN OUTPUT- UND DEN DAY-FILE SCHREIBEN
      WRITE (YMSG(2),11) '*****UP: ',YUP,'**INT-VARIABLE: ',YVAR,
     &                   '**WERT = ',IWERT,'*****'
   11 FORMAT (A,A8,A,A8,A,I20,A)
      DO I = 1,2
         CALL REMARK(YMSG(I))
      ENDDO

      RETURN
      END SUBROUTINE PRIV
