      SUBROUTINE PRRV ( YUP, YVAR, RWERT )
C
C@(#) BIBLIOTHEK EM: EUROPA-MODELL / DEUTSCHLAND-MODELL
C@(#) MODUL PRRV.F, V2.12 VOM 4/27/94, EXTRAHIERT AM 4/28/94
C
C**** PRRV     -   UP:DRUCKEN VON NAMEN UND WERT EINER REAL-VARIABLEN
C****                 (DEBUG)
C**
C**   AUFRUF   :   CALL PRRV ( YUP, YVAR, RWERT )
C**   ZWECK    :   AUSGABE DES NAMENS UND WERTES EINER REAL-VARIABLEN
C**                SOWOHL IN DEN DAY-FILE,ALS AUCH AUF FILE OUTPUT
C**   EXTERNALS:   REMARK
C**   EINGABE-
C**   PARAMETER:   YUP   -   NAME DES RUFENDEN UNTERPROGRAMMES
C**                YVAR  -   NAME DER REAL-VARIABLEN
C**                RWERT -   WERT DER REAL-VARIABLEN
C**   VERFASSER:   VOLKER WOHLGEMUTH,F3
C
      IMPLICIT NONE
C
      REAL,          INTENT(IN) :: RWERT
      CHARACTER*(*), INTENT(IN) :: YUP, YVAR
C
      CHARACTER*80 :: YMSG(2)
      INTEGER      :: I

C     YMSG VORBESETZEN
      YMSG(1) = '***** MESSAGE FROM USER-SUPPORT *****'
      DO I = 1,80
         YMSG(2)( I: I) = ' '
      ENDDO

C     YUP, YVAR , RWERT IN DEN OUTPUT- UND DEN DAY-FILE SCHREIBEN
      WRITE (YMSG(2),11) '*****UP: ',YUP,'**REAL-VARIABLE: ',YVAR,
     &                   '**WERT = ',RWERT,'*****'
   11 FORMAT (A,A8,A,A8,A,E20.14,A)
      DO I = 1,2
         CALL REMARK(YMSG(I))
      ENDDO 

      RETURN
      END SUBROUTINE PRRV
