      SUBROUTINE PSENDALL2I(BUF)
      IMPLICIT NONE
C
      INCLUDE "parorg.h"
C 
      INTEGER, INTENT(IN) :: BUF
      INTEGER :: I
C
      DO I=1,NPROC
         IF (I-1.NE.MYID)THEN
            DEST=I-1
            CALL MPI_SEND(BUF,COUNT,MPI_INTEGER,DEST,TYPE,
     &           MPI_COMM_WORLD,IERROR)
         ENDIF
      ENDDO
C
      RETURN
      END SUBROUTINE PSENDALL2I
