      SUBROUTINE PSENDL(BUF)
      IMPLICIT NONE
C      
      INCLUDE "parorg.h"
C
      LOGICAL, INTENT(IN) :: BUF
C
      CALL MPI_ISEND(BUF,COUNT,MPI_LOGICAL,DEST,TYPE,
     &     MPI_COMM_WORLD,REQUEST(REQUESTNR),IERROR)
      REQUESTNR=REQUESTNR+1
C
      RETURN
      END SUBROUTINE PSENDL
