      SUBROUTINE PSENDALLI(BUF)
      IMPLICIT NONE
C
      INCLUDE "parorg.h"
C
      INTEGER, INTENT(IN) :: BUF
      INTEGER :: ROOT

      ROOT=0
      CALL MPI_BCAST(BUF,COUNT,MPI_INTEGER,ROOT,MPI_COMM_WORLD,
     &      IERROR)
      RETURN
      END SUBROUTINE PSENDALLI
