      SUBROUTINE PSENDR(BUF)
      IMPLICIT NONE
C
      INCLUDE "parorg.h"
C
      REAL, INTENT(IN) :: BUF
C
      CALL MPI_ISEND(BUF,COUNT,P_REAL,DEST,TYPE,
     &     MPI_COMM_WORLD,REQUEST(REQUESTNR),IERROR)
      REQUESTNR=REQUESTNR+1
C
      RETURN
      END
