      SUBROUTINE READGTS
C
C**** *READGTS* - READ IN TIME SERIES OF GREENHOUSE GASES
C
C      U.  SCHLESE    DKRZ - HAMBURG    JUNE 95
C      GEAENDERT V. R.PODZUN FUER REMO 16.01.02
C      2007
C
C
C      METHOD.
C      -------
C
C      TIME SERIES OF VARIOUS GREENHOUSE GASES ARE READ FROM
C      UNITS *NGTS* (CO2, CH4 AND N2O) AND *NCTS* (CFC'S).
C      THE DATA ARE STORED IN COMMON *COMGTS*.
C
C      INTERPOLATION IN TIME IS PERFORMED IN *PREPGRG* IN
C      THE TIME LOOP.
C
C      INTERFACE.
C      ----------
C
C     *READGTS* IS CALLED FROM PHYEC AT THE BEGINNING OF A RUN.
C
      IMPLICIT NONE
C
      INCLUDE "parorg.h"
      INCLUDE "corg.h"
      INCLUDE "COMGTS"
      CHARACTER :: YPFAD*128, YBTEXT*136
      INTEGER   :: I, ILYBTEX, ILYDCAT, ILYDNAM, ILYPFAD, ISTAT, IYEAR, 
     &             NGTS, JR
      INTEGER, EXTERNAL :: LENCH
C
C     SET UNIT NUMBERS
C
C     ASCII FILE  GREENHOUSE GASES AND CFC'S
C
      NGTS=10
C
C
C     -----------------------------------------------------------
C
C*         1.    READ TIME SERIES.
C                ---- ---- ------
C
      IF (MYID.EQ.0) THEN

         YBTEXT  = ' '
C
C        LAENGE DES CATALOG-NAMENS FESTSTELLEN
         ILYDCAT = LENCH(YGDCAT)
C
C        PFADNAME DER DATEI ERSTELLEN
         ILYDNAM = LENCH(YGDNAM)
         YPFAD   = YGDCAT(1:ILYDCAT)//YGDNAM(1:ILYDNAM)
         ILYPFAD = LENCH(YPFAD)
         YBTEXT = 'OPEN:   '//YPFAD
         ILYBTEX = LENCH(YBTEXT)
         CALL PRTLOG(YBTEXT(1:ILYBTEX))
         OPEN(NGTS,FORM='FORMATTED',FILE=YPFAD(1:ILYPFAD),IOSTAT=ISTAT)
         IF (ISTAT.NE.0) THEN
            PRINT *,'READGTS: FEHLER IN OPEN'
            STOP
         ENDIF
C
C        SKIP HEADER LINES
C
         READ(NGTS,9001)
         READ(NGTS,9001)
         READ(NGTS,9001)
         READ(NGTS,9001)
C
         DO JR=JPGTS1,JPGTS2
            READ(NGTS,*) IYEAR, CO2TS(JR), CH4TS(JR), AN2OTS(JR),
     &           (CFCTS(I,JR),I=1,2)
            IF (JR.EQ.JPGTS1.AND.JR.NE.IYEAR) THEN
               PRINT *,'JPGTS1 UNGLEICH IYEAR => COMGTS ANPASSEN !!!'
               STOP 'FEHLER'
            ENDIF
         ENDDO
C
         CLOSE(NGTS)
      ENDIF

      COUNT=JPGTS2-JPGTS1+1     !HG
      CALL PSENDALLR(CO2TS)
C      CALL PSTOP
      CALL PSENDALLR(CH4TS)
C      CALL PSTOP
      CALL PSENDALLR(AN2OTS)
C      CALL PSTOP
      DO I=1, 2
         CALL PSENDALLR(CFCTS(I,JPGTS1)) !HG
C      CALL PSTOP
      ENDDO
C
 9001 FORMAT(A)
C
C     -----------------------------------------------------------------

      RETURN
      END SUBROUTINE READGTS
