      SUBROUTINE SEND(NUDAT, YDNAM, YDCAT)
C
C**** SEND     -   UP: OEFFNEN EINER UNFORMATIERTEN OUTPUT-DATEI
C**   AUFRUF   :   SUBROUTINE SEND(NUDAT, YDNAM, YDCAT)
C**
C**   ENTRIES  :   KEINE
C**   ZWECK    :   OEFFNEN EINER UNFORMATIERTEN OUTPUT-DATEI
C**   VERSIONS-
C**   DATUM    :   22.01.99
C**
C**   EXTERNALS:   LENCH, PRTLOG
C**
C**   EINGABE-
C**   PARAMETER:   NUDAT:   LOGISCHE EINHEIT (UNIT-NUMBER) DER ERGEB-
C**                         NISDATEI
C**                YDNAM:   PERMANENTER/LOKALER DATEI-NAME
C**                YDCAT:   CATALOG, IN DEM DIE DATEI GESPEICHERT WIRD
C**   AUSGABE-
C**   PARAMETER:   KEINE
C**
C**   COMMON-
C**   BLOECKE  :   KEINE
C**
C**   METHODE  :   KEINE
C**
C**   FEHLERBE-
C**   HANDLUNG :   STOP IM FEHLERFALL
C**   VERFASSER:   R. PODZUN
C
      IMPLICIT NONE
C
      INTEGER,       INTENT(IN) :: NUDAT
      CHARACTER*(*), INTENT(IN) :: YDNAM, YDCAT
C
      CHARACTER :: YPFAD*80, YBTEXT*96, YRM*5
      INTEGER   :: ILYDCAT, ILYDNAM, ILYPFAD, ISTAT
      INTEGER, EXTERNAL :: LENCH
C
      YBTEXT  = ' '
C
C     LAENGE DES CATALOG-NAMENS FESTSTELLEN
      ILYDCAT  = LENCH(YDCAT)
C
C     PFADNAME FUER DATEI ERSTELLEN
      ILYDNAM  = LENCH(YDNAM)
      YPFAD    = YDCAT(1:ILYDCAT)//YDNAM(1:ILYDNAM)
      ILYPFAD  = LENCH(YPFAD)
C
      YBTEXT   = 'SAVE:   '//YPFAD
      OPEN(NUDAT,FILE=YPFAD(1:ILYPFAD),FORM='UNFORMATTED',
     &           POSITION='APPEND',IOSTAT=ISTAT)
C
      CALL PRTLOG(YBTEXT)
C
      IF (ISTAT.NE.0) THEN
         WRITE(YRM, '(I5)') ISTAT
         YBTEXT = 'SEND: FEHLER BEIM OPEN; FEHLER-NR: '//YRM
         CALL PRTLOG(YBTEXT)
         STOP 'ERROR'
      ENDIF
C
      RETURN
      END SUBROUTINE SEND
