      SUBROUTINE SETIA ( IAR,IDIM,IWERT )
C
C@(#) BIBLIOTHEK EM: EUROPA-MODELL / DEUTSCHLAND-MODELL
C@(#) MODUL SETIA.F, V2.12 VOM 4/27/94, EXTRAHIERT AM 4/28/94
C
C**** SETIA    -   UP:WERT FUER EIN INTEGER-FELD ZUWEISEN (DEBUG)
C**
C**   AUFRUF   :   CALL SETIA ( IAR,IDIM,IWERT )
C**   ZWECK    :   INTEGERFELD MIT WERTEN BESETZEN
C**   EINGABE-
C**   PARAMETER:   IAR  -  REAL-FELD,DAS BESETZT WERDEN SOLL
C**                IDIM -  ANZAHL DER ZU BESETZENDEN FELDELEMENTE
C**                IWERT-  REAL-WERT FUER DIE VORBESETZUNG
C**
C**   VERFASSER:   VOLKER WOHLGEMUTH,F3
C
      IMPLICIT NONE
C
      INTEGER, INTENT(IN)    :: IDIM,IWERT
      INTEGER, INTENT(INOUT) :: IAR(IDIM)
C
      INTEGER :: II

      IF (IDIM.GE.1) THEN
         DO II  = 1,IDIM
            IAR  (II) = IWERT
         ENDDO
      ELSE
         PRINT*,'***** FEHLER IN UP *SETIA* :  IDIM KLEINER 1 *****'
      END IF

      RETURN
      END SUBROUTINE SETIA
