      SUBROUTINE SETRA ( RAR, IDIM, RWERT )
C
C**** SETRA    -   UP:WERT FUER EIN REAL-FELD ZUWEISEN
C**
C**   AUFRUF   :   CALL SETRA ( RAR, IDIM, RWERT )
C**   ZWECK    :   REALFELD MIT EINEM WERT BESETZEN
C**   EINGABE-
C**   PARAMETER:   RAR  -  REAL-FELD,DAS BESETZT WERDEN SOLL
C**                IDIM -  ANZAHL DER ZU BESETZENDEN FELDELEMENTE
C**                RWERT-  REAL-WERT FUER DIE VORBESETZUNG
C**
C**   VERFASSER:   VOLKER WOHLGEMUTH,F3

      IMPLICIT NONE
 
      INTEGER, INTENT(IN)    :: IDIM
      REAL,    INTENT(IN)    :: RWERT
      REAL,    INTENT(INOUT) :: RAR(IDIM)

      INTEGER :: II

      DO II  = 1,IDIM
         RAR  (II) = RWERT
      ENDDO

      RETURN
      END SUBROUTINE SETRA
