C
C     CB *UNITZR* ENTHAELT DIE UNITNUMMERN DER ZEITREIHEN-DATEIEN
C     *UNITZR* IMMER MIT *CORG* VERWENDEN
C
      INTEGER ::        NUEDAT(NZMXVM), NUNDAT(NZMXVN)
C
      COMMON / UNITZR / NUEDAT        , NUNDAT
C
C     VERFASSER: R. PODZUN
C
