C
      CHARACTER*7        YINPUT , YUAUFTR
      COMMON / UNITCH /  YINPUT , YUAUFTR
C
C**** UNITCH   -   CB:NAMEN UND LOGICAL UNITS DER EM-DATEIEN
C****                 *UNITCH* UND *UNITNR* GEHOEREN ZUSAMMEN
C**   BESCHREIBUNG DER VARIABLEN:
C**
C**                FORMATTIERTE DATEIEN:
C**   YINPUT   :   INPUT-DATEI FUER NAMELIST-VARIABLEN
C**   YUAUFTR  :   DATEI FUER PROTOKOLLIERUNG DES AUFTRAGS
C**
C**   VERFASSER:   D.MAJEWSKI / R.PODZUN
