      BLOCK DATA VARN2
C
      IMPLICIT NONE
C
      INCLUDE "corg.h"
      INCLUDE "corg2.h"
C
      DATA      YTVARND              / 'T       ','U       ','V       ',
     1                                 'QD      ','QW      ','PS      ',
     2                                 'VERVEL  ','TSECH   ','TSLECH  ',
     3                                 'TSWECH  ','TSIECH  ','WSECH   ',
     4                                 'SN      ','APRL    ','APRC    ',
     5                                 'APRS    ','VDIS    ','AHFS    ',
     6                                 'AHFL    ','USTAR3  ','RUNOFF  ',
     7                                 'ACLC    ','ACLCV   ','ACLCOV  ',
     8                                 'U10     ','V10     ','TEMP2   ',
     9                                 'DEW2    ','TSURF   ','TD      ',
     A                                 'WIND10  ','BLA     ','AZ0     ',
     1                                 'ALBECH  ','ALBEDO  ','SRADS   ',
     2                                 'TRADS   ','SRAD0   ','TRAD0   ',
     3                                 'USTR    ','VSTR    ','EVAP    ',
     4                                 'TDCL    ','SRAFS   ','TRAFS   ',
     5                                 'SRAF0   ','TRAF0   ','SCLFS   ',
     6                                 'TCLFS   ','SCLF0   ','TCLF0   ',
     7                                 'WL      ','USTRGW  ','VSTRGW  ',
     8                                 'VDISGW  ','VGRAT   ','VAROR   ',
     9                                 'VLT     ','T2MAX   ','T2MIN   ',
     B                                 'SRAD0U  ','SRADSU  ','TRADSU  ',
     1                                 'TSN     ','TD3     ','TD4     ',
     2                                 'TD5     ','SEAICE  ','SICED   ',
     3                                 'FOREST  ','TEFF    ','TSMAX   ',
     4                                 'TSMIN   ','WIMAX   ','TOPMAX  ',
     5                                 'SNMEL   ','TSLIN   ','DSNAC   ',
     6                                 'ACLCAC  ','TKE     ','FAO     ',
     7                                 'WSMX    ','TMCM    ','TMCH    ',
     8                                 'QVI     ','ALWCVI  ','GLAC    ',
     9                                 'PHI     ','RLA     ','FIB     ',
     C                                 'FI      ','QDB     ','DRAIN   ',
     1                                 'USTRL   ','USTRW   ','USTRI   ',
     2                                 'VSTRL   ','VSTRW   ','VSTRI   ',
     3                                 'EVAPL   ','EVAPW   ','EVAPI   ',
     4                                 'AHFSL   ','AHFSW   ','AHFSI   ',
     5                                 'AZ0L    ','AZ0W    ','AZ0I    ',
     6                                 'ALSOL   ','ALSOW   ','ALSOI   ',
     7                                 'QDBL    ','QDBW    ','QDBI    ',
     8                                 'AHFICE  ','QRES    ','QDBOXS  ',
     9                                 'QWBOXS  ','EKBOXS  ','FHBOXS  ',
     D                                 'FIBOXS  ','WI3     ','WI4     ',
     1                                 'WI5     ','WI      ','WICL    ',
     2                                 'PSRED   ','FTKVM   ','FTKVH   ',
     3                                 'VBM10M  ','GHPBL   ','CAPE    ',
     4                                 'WS1     ','WS2     ','WS3     ',
     5                                 'WS4     ','WS5     ','DZR     ',
     6                                 'DZS     ','FKSAT   ','FMPOT   ',
     7                                 'BCLAPP  ','VPOR    ','ETRANS  ',
     8                                 'EBSOIL  ','ESNOW   ','ESKIN   ',
     9                                 'ERES    ','QI      ','QIVI    ',
     E                                 'QIBOXS  ','RPRAC   ',
     1                                                     5*'        '/
C
      DATA      YDVARND              / 'U       ','V       ','T       ',
     1                                 'QD      ','QW      ','PS      ',
     2                                 'TSECH   ','TSLECH  ','TSWECH  ',
     3                                 'TSIECH  ','TSN     ','TD3     ',
     4                                 'TD4     ','TD5     ','WSECH   ',
     5                                 'SN      ','WL      ','APRL    ',
     6                                 'APRC    ','APRS    ','EVAP    ',
     7                                 'U10     ','V10     ','TEMP2   ',
     8                                 'DEW2    ','T2MAX   ','T2MIN   ',
     9                                 'WIMAX   ','TSMAX   ','TSMIN   ',
     A                                 'ACLC    ','ACLCV   ','ACLCOV  ',
     1                                 'ACLCAC  ','ALBECH  ','SRADS   ',
     2                                 'TRADS   ','SRAD0   ','TRAD0   ',
     3                                 'USTR    ','VSTR    ','AZ0     ',
     4                                 'AHFL    ','AHFS    ','ALBEDO  ',
     5                                 'FIB     ','BLA     ','RUNOFF  ',
     6                                 'PHI     ','RLA     ','TD      ',
     7                                 'TDCL    ','WS1     ','WS2     ',
     8                                 'WS3     ','WS4     ','WS5     ',
     9                                 'ETRANS  ','EBSOIL  ','ESNOW   ',
     B                                 'ESKIN   ','ERES    ','QI      ',
     1                                 'RPRAC   ',
     2                                                    13*'        '/
C
      DATA      YMVARND              / 'QDB     ','QDBL    ','QDBW    ',
     1                                 'QDBI    ','PS      ','TSECH   ',
     2                                 'TSLECH  ','TSWECH  ','TSIECH  ',
     3                                 'WSECH   ','SN      ','APRL    ',
     4                                 'APRC    ','APRS    ','VDIS    ',
     5                                 'AHFS    ','AHFL    ','PSRED   ',
     6                                 'USTAR3  ','RUNOFF  ','DRAIN   ',
     7                                 'ACLCV   ','ACLCOV  ','U10     ',
     8                                 'V10     ','TEMP2   ','DEW2    ',
     9                                 'TSURF   ','TD      ','WIND10  ',
     A                                 'AZ0     ','AZ0L    ','AZ0W    ',
     1                                 'AZ0I    ','ALBECH  ','ALBEDO  ',
     2                                 'ALSOL   ','ALSOW   ','ALSOI   ',
     3                                 'SRADS   ','TRADS   ','SRAD0   ',
     4                                 'TRAD0   ','USTR    ','USTRL   ',
     5                                 'USTRW   ','USTRI   ','VSTR    ',
     6                                 'VSTRL   ','VSTRW   ','VSTRI   ',
     7                                 'EVAP    ','EVAPL   ','EVAPW   ',
     8                                 'EVAPI   ','TDCL    ','TRAFS   ',
     9                                 'TRAF0   ','TCLFS   ','TCLF0   ',
     B                                 'WL      ','VGRAT   ','VLT     ',
     1                                 'T2MAX   ','T2MIN   ','SRAD0U  ',
     2                                 'SRADSU  ','TRADSU  ','TSN     ',
     3                                 'TD3     ','TD4     ','TD5     ',
     4                                 'SEAICE  ','SICED   ','TEFF    ',
     5                                 'TSMAX   ','TSMIN   ','WIMAX   ',
     6                                 'TOPMAX  ','SNMEL   ','TSLIN   ',
     7                                 'AHFICE  ','QRES    ','DSNAC   ',
     8                                 'QVI     ','ALWCVI  ','BFLHS   ',
     9                                 'BFLHSL  ','BFLHSW  ','BFLHSI  ',
     C                                 'BFLQDS  ','BFLQDSL ','BFLQDSW ',
     1                                 'BFLQDSI ','QDBOXS  ','QWBOXS  ',
     2                                 'EKBOXS  ','FHBOXS  ','FIBOXS  ',
     3                                 'TLAMBDA ','DLAMBDA ','PORVOL  ',
     4                                 'WI3     ','WI4     ','WI5     ',
     5                                 'WI      ','WICL    ','U10ER   ',
     6                                 'V10ER   ','VBM10M  ','GHPBL   ',
     7                                 'CAPE    ','WS1     ','WS2     ',
     8                                 'WS3     ','WS4     ','WS5     ',
     9                                 'ETRANS  ','EBSOIL  ','ESNOW   ',
     D                                 'ESKIN   ','ERES    ','QIVI    ',
     1                                                    17*'        '/
C
      DATA      YNVARND              / 'TSLECH  ','WSECH   ','APRL    ',
     1                                 'APRC    ','EVAP    ','RUNOFF  ',
     2                                 'DRAIN   ','TEMP2   ','DEW2    ',
     3                                 'APRS    ','T2MAX   ','T2MIN   ',
     4                                                   128*'        '/
      END BLOCK DATA VARN2
